spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.101/sell?characterEncoding=UTF-8&useSSL=false
 ######    url: jdbc:mysql://192.168.0.105/sell?characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.MySQLDialect
    ###hibernate:
      ##naming:
        ##physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    time-zone: GMT+8
server:
  servlet:
    context-path: /sell


      
        
      
